galaxy_info:
  author: "Sobit Amirov"
  description: "Docker installation on Ubuntu and RedHat based systems"

  license: "MIT"

  min_ansible_version: "2.15.0"

  galaxy_tags:
    - linux
    - docker

dependencies: []
